version: "3"

services:
  chatgpt-web-share:
    # image: ghcr.io/moeakwak/chatgpt-web-share:latest
    container_name: chatgpt-web-share
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - 8080:80
    volumes:
      - ./deploy/data:/data
      - ./deploy/config.yaml:/app/backend/api/config/config.yaml
      - ./deploy/logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    # ports:
    # - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    #      - NETWORK_PROXY_SERVER=http://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
